DATA:
  DIM: 2 # data dimension
  BATCH_SIZE: 32 #16
  TEST_BATCH_SIZE: 128 #16
  DATA_PATH: "/media/data/alex_johannes/data/OCTA-500_6mm/train_data"
  SOURCE_DATA_PATH: "/media/data/alex_johannes/data/OCTA-500_6mm/train_data" # Path to dataset, could be overwritten by command line argument
  NUM_SOURCE_SAMPLES: 100
  NUM_TARGET_SAMPLES: 100
  TARGET_DATA_PATH: "/media/data/alex_johannes/data/OCTA-500_6mm/train_data"
  #TEST_DATA_PATH: "/home/iterm/johannes.paetzold/data/synthetic_eye_vessels_small/test_data"
  TEST_DATA_PATH: "/media/data/alex_johannes/data/OCTA-500_6mm/test_data"
  DATASET: "real_eye_vessel_dataset" # Dataset name
  IMG_SIZE: [128, 128] # Input image size
  NUM_WORKERS: 4 # Number of data loading threads
  SEED: 10 # random seed for reproducibility

MODEL:
  NUM_CLASSES: 2 # Number of classes, overwritten in data preparation

  ENCODER:
    TYPE: deformable_transformer_backbone
    NAME: deformable_transformer_backbone
    HIDDEN_DIM: 512 #128 #256 #768
    POSITION_EMBEDDING: sine
    NUM_FEATURE_LEVELS: 3
    BACKBONE: resnet101
    BACKBONE_INIT_WEIGHTS: ResNet101_Weights
    MASKS: False
    DILATION: False

    # parameters used else where
    IN_CHANS: 3
    DEPTHS: [4, 4, 8, 8, 18]

  DECODER:
    TYPE: deformable_transformer
    NAME: deformable_transformer
    HIDDEN_DIM: 512 #128 #256 #768
    NHEADS: 8
    ENC_LAYERS: 3 #4 #2
    DEC_LAYERS: 3 #4 #2
    DIM_FEEDFORWARD: 1024 #128 #512 #2048
    DROPOUT: 0.1 # 0.0
    ACTIVATION: relu
    NUM_FEATURE_LEVELS: 4
    DEC_N_POINTS: 4
    ENC_N_POINTS: 4
    TWO_STAGE: False
    # NUM_QUERIES: 21
    AUX_LOSS: False
    WITH_BOX_REFINE: False
    # RLN_TOKEN: True

    OBJ_TOKEN: 80
    RLN_TOKEN: 2
    DUMMY_TOKEN: 0

    RLN_ATTN: True # only do comb RLN_ATTN True + RLN_TOKEN 0 and reverse

  MATCHER:
    C_CLASS: 3
    C_NODE: 5

TRAIN:
  EPOCHS: 100
  LR: 2e-4
  LR_BACKBONE: 2e-5
  LR_DOMAIN: 2e-4
  ALPHA_COEFF: 0.0
  TRAIN_CNN_BACKBONE: True
  TRAIN_ENCODER: True
  TRAIN_DECODER: True
  WEIGHT_DECAY: 1e-3
  LR_DROP: 180
  CLIP_MAX_NORM: 0.1 # hardcoded
  NUM_EDGE_SAMPLES: 9999
  EDGE_UPSAMPLING: True # Only combine True with NUM_EDGE_SAMPLES=9999
  EDGE_SAMPLE_RATIO: 0.2
  EDGE_SAMPLE_RATIO_INTERVAL: 0.025
  EDGE_SAMPLING_MODE: none

  SAVE_PATH: "./trained_weights/" # save path for the checkpoint, log and val results
  VAL_INTERVAL: 1 # validation interval
  SAVE_VAL: False # save validation data
  RECOVER_OPTIMIZER_STATE: False
  DOMAIN_WEIGHTING: [0.5, 0.5]
  

  # loss weight
  LOSSES: ["boxes", "class", "cards", "nodes", "edges", "domain"]
  W_BBOX: 2.0
  W_CLASS: 3.0
  W_CARD: 1.0
  W_NODE: 5.0
  W_EDGE: 5.0
  W_DOMAIN: 1.0

log:
  exp_name: "exp"
  message: "exp"
